### ISSUE TITLE
Fix/regenerate thumbnails of images first added to INHS-IC TW project

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/INHS-Insect-Collection-Data-Curation#10]
Pages 1-596 in the INHS-IC project.
First image: https://sfg.taxonworks.org/images/591404
Second image: https://sfg.taxonworks.org/images/606777

**Comment by mjy** [comment]
Fixable when 0.41.1 is live.

**Comment by mjy** [comment]
@tmcelrath Done!

**Comment by tmcelrath** [comment]
Yay! Thanks much.
