### ISSUE TITLE
2024-04-27 via Mesibov on GBIF data: occurrences with *only* previousIdentifications

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/INHS-Insect-Collection-Data-Curation#61]
| occurrenceID  | higherClassification | previousIdentifications |
| --- | --- | --- |
| 27df421d-4976-4904-9780-ab63eaa44f6e |    | Ceraclea maculata (Banks, 1899) by Morse on 1975 |
| 34315fe4-d327-4ba6-b9a5-43860c16b308 | "" | Bombus kirbiellus by Schrage on 2023-4 \| Bombus on 2006  |
| 66c0bc54-a2a8-4f44-9bcb-8d0a6f71f8ae | "" | Bombus on 2006 |
| 7e4573d2-bb41-4166-a69d-aa1b119da1c9 | "" | Epitragus antillensis \| Epitragus antillensis \| Epitragini by Wirth on 2022 | 
| 927a3bcd-145c-4ce5-9973-db043651dc43 |    | Hemicrepidius decoloratus (Say, 1836) by Lane on 1944 |
| b1198156-06c9-4b48-b854-55dd5b0d9c1d |    | Hemicrepidius decoloratus (Say, 1836) by Lane on 1944 |
| b8017f76-13cf-464f-a7f7-5e89ba51187a |    | Hemicrepidius decoloratus (Say, 1836) on 1960 | 
| dad8e892-81b7-408a-9f94-8af5d15df2e2 |    | Hemicrepidius decoloratus (Say, 1836) by Hart |
| e5507676-e756-48ce-a9e3-b60efa542989 |    | Hemicrepidius decoloratus (Say, 1836) by Lane on 1944 |
| ec7100d8-b595-4bee-8394-f039b3397bc7 |    | Hemicrepidius decoloratus (Say, 1836) by Lane on 1944 |

**Comment by tmcelrath** [comment]
All fixed, or OTUS are not interpreted by GBIF for some reason (e.g. Prosternini/Dendrometrine) is not exported/interpreted by GBIF.
