### ISSUE TITLE
 2024-04-27 via Mesibov on GBIF data: Lasioglossum lectotype duplication?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/INHS-Insect-Collection-Data-Curation#65]
occurrenceID | scientificName | typeStatus
5e8a71e8-421c-4c3e-a896-270a80ffd8ed | Lasioglossum (Dialictus) platyparium (Robertson, 1895) | lectotype of Paralictus platyparium Robertson, 1895
49efb31b-0152-4589-aa22-59d500a32bd1 | Lasioglossum (Dialictus) platyparium (Robertson, 1895) | lectotype of Paralictus platyparium Robertson, 1895

5705538 | PreservedSpecimen | 5e8a71e8-421c-4c3e-a896-270a80ffd8ed | INHS Insect Collection 179613 | | 1 | Pin | Adult(s) | Female | United States | Illinois | Macoupin | 1887-07-29/1887-07-29 | 1887 | 7 | 29 | 210 | 210 | | | | | | | 29 July 1887 | Carlinville | | | | | | | 2006 | iczn | Animalia | Arthropoda | Insecta | Hymenoptera | Animalia | Arthropoda | Insecta | Hymenoptera | Apocrita | Apoidea | Halictidae | Halictinae | Halictini | Lasioglossum | Dialictus | Halictidae | Lasioglossum | platyparium | | Lasioglossum (Dialictus) platyparium (Robertson, 1895) | (Robertson, 1895) | species | | lectotype of Paralictus platyparium Robertson, 1895 | INHS | http://grbio.org/institution/illinois-natural-history-survey | Robertson, Charles | | | | | 39.27972 | - 89.88167 | 10000.0 | A geospatial point translated from verbatim values recorded on human-readable media (e.g. paper specimen label, field notebook). | Physical collection object. | Favret, Colin | 2021-04-06 14:58:41 UTC | present | |
5705535 | PreservedSpecimen | 49efb31b-0152-4589-aa22-59d500a32bd1 | INHS Insect Collection 179614 | | 1 | Pin | Adult(s) | Female | United States | Illinois | Macoupin | 1887-05-18 | 1887 | 5 | 18 | 138 | | | | | | | | | Carlinville | | | | | | | 2006 | iczn | Animalia | Arthropoda | Insecta | Hymenoptera | Animalia | Arthropoda | Insecta | Hymenoptera | Apocrita | Apoidea | Halictidae | Halictinae | Halictini | Lasioglossum | Dialictus | Halictidae | Lasioglossum | platyparium | | Lasioglossum (Dialictus) platyparium (Robertson, 1895) | (Robertson, 1895) | species | | lectotype of Paralictus platyparium Robertson, 1895 | INHS | http://grbio.org/institution/illinois-natural-history-survey | | | N39.27972o W89.88167o | N39.27972o | W89.88167o | 39.27972 | -89.88167 | 10000.0 | A geospatial point translated from verbatim values recorded on human-readable media (e.g. paper specimen label, field notebook). | Physical collection object. | Higgs, Kate | | present | |

**Comment by tmcelrath** [comment]
Fixed. Was under wrong type name.
