### ISSUE TITLE
2024-04-27 via Mesibov on GBIF data: malformed type status

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/INHS-Insect-Collection-Data-Curation#66]
occurrenceID | type status

d3bc58ba-e6f3-4ded-acd3-d9a53e0ca9f5 | paratype | paratype
0c78dc8b-ee7c-49b4-84ae-0d1b5a86ec2 | paratypes | paratypes | paratypes

**Comment by tmcelrath** [comment]
Fixed.

**Comment by tmcelrath** [comment]
@mjy is there any reason to have multiple type statuses on a type object? We may want to constrain to one/object.
