### ISSUE TITLE
2024-04-27 via Mesibov on GBIF data:  identifiedByID entries need to have ORCID URLs to be correctly formed identifiers:

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/INHS-Insect-Collection-Data-Curation#68]
# records: field value

11: orcid.org/0000-0001-7185-4511
12:  orcid.org/0000-0002-3293-4794
1:  orcid.org/0000-0002-3293-4794 | https://orcid.org/0000-0002-3341-3560 8 orcid.org/0000-0002-5086-7847

**Comment by tmcelrath** [comment]
All fixed. Should be fixed on re-index.
