### ISSUE TITLE
Delete ghost records

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/INHS-Insect-Collection-Data-Curation#76]
830 "Ghost" Records that can be destroyed. No catalog number and no images or determinations: https://sfg.taxonworks.org/tasks/collection_objects/filter?per=50&depictions=false&local_identifiers=false&taxon_determinations=false&with_buffered_determinations=false&page=3&extend%5B%5D=dwc_occurrence&extend%5B%5D=repository&extend%5B%5D=current_repository&extend%5B%5D=collecting_event&extend%5B%5D=taxon_determinations&extend%5B%5D=identifiers&exclude%5B%5D=object_labels

**Comment by mjy** [comment]
```ruby
p = {
depictions: false,
local_identifiers: false,
taxon_determinations: false,
with_buffered_determinations: false
}

q = ::Queries::CollectionObject::Filter.new(p)

q.all.destroy_all

```

**Comment by tmcelrath** [comment]
Need to make sure there is no local identifier as well.

**Comment by tmcelrath** [comment]
Yeah looks right.

**Comment by mjy** [comment]
Done.

<img width="560" alt="Screenshot 2024-05-13 at 11 41 15 AM" src="https://github.com/SpeciesFileGroup/INHS-Insect-Collection-Data-Curation/assets/22600/dfe43af2-35f9-4a31-a876-61f5f752c39b">
