### ISSUE TITLE
"Issues" with identifiers

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/INHS-Insect-Collection-Data-Curation#8]
Something is wrong with some of the identifiers added during the migration [@proceps](https://github.com/proceps) - for example, this one gives a Internal server error every time I try to load it.
![image](https://github.com/SpeciesFileGroup/INHS-Insect-Collection-Data-Curation/assets/11411328/6f58b368-d8dc-405b-ac9b-0ffb2bec1db6)

**Comment by tmcelrath** [comment]
Proceps: 

An ActionView::Template::Error occurred in identifiers#index:
undefined method `is_virtual?' for nil:NilClass

  if identifier.namespace.is_virtual?
                         ^^^^^^^^^^^^
app/helpers/identifiers_helper.rb:7:in `identifier_tag'
[@mjy1](https://github.com/mjy1) could you check what is the problem with the identifier handling?

**Comment by tmcelrath** [comment]
@proceps : is it related to import indentifiers, which do not have namespece?

**Comment by tmcelrath** [comment]
That would make sense since these just had an "Accession Code" identifier.

**Comment by proceps** [comment]
![image](https://github.com/SpeciesFileGroup/INHS-Insect-Collection-Data-Curation/assets/5597748/a4c651f3-fea2-40b7-ae24-25048de81cf6)
I do not have a problem loading identifiers... Browser cache?

**Comment by tmcelrath** [comment]
It works for me now too? I guess we can close!
